#!/usr/bin/env bash

# # What is run, and in which order, by 'rice::run'
# 
# ## Rules
#
# name    := [A-Za-z_]+
# pattern := name | pattern:pattern
# module  := name | name:pattern
# option  := -m | -x
#
# let OPTIONS := option... | NONE
# let MODULES := module...
# let PATTERN := pattern
# let PREFIX  := pattern (a prefix of PATTERN)
#
# executing 'rice::module OPTIONS module...'
#   adds all 'module', to 'MODULES', with option 'OPTIONS'
#
# executing 'rice::run'
#	runs all 'module', maching exactly 'name',
#		without option '-x',
#		in 'MODULES', in order
#
# executing 'rice::run PATTERN'
#   runs all 'module', matching exactly 'name' or 'name:PATTERN' or 'name:PREFIX',
#		 without option '-x',
#		 in 'MODULES', in order
#
# options:
#	-a --all	also run modules added with option '-x/--explicit'
#
#
# ## Example
# 
# PATTERN='' (only top-level modules)
# 1. activity
#
# PATTERN='setup_a'
# 1. activity
# 2. activity:setup_a
#
# PATTERN='machine_a'
# 1. activity
# 2. activity:machine_a
#
# PATTERN='setup_a:machine_a':
# 1. activity
# 2. activity:setup_a
# 3. activity:setup_a:machine_a
# 
# PATTERN='setup_a:machine_b':
# 1. activity
# 2. activity:setup_a
# 3. activity:setup_a:machine_b
#
# PATTERN='machine_a:setup_a' (works but makes little sense with these specific names)
# 1. activity
# 2. activity:machine_a
# 3. activity:machine_a:setup_a
#

# Group 1

rice::add activity
activity() {
	rice::exec true
}

# Group 2

rice::add activity:setup_a
activity:setup_a() {
	rice::exec true
}

rice::add activity:setup_a:machine_a
activity:setup_a:machine_a() {
	rice::exec true
}

rice::add activity:setup_a:machine_b
activity:setup_a:machine_b() {
	rice::exec true
}

# Group 3

rice::add activity:machine_a
activity:machine_a() {
	rice::exec true
}

rice::add activity:machine_a:setup_a
activity:machine_a:setup_a() {
	rice::exec true
}

