#!/usr/bin/env bash

meta:system_a() {
	rice::exec true
}

activity_a() {
	rice::exec true
}

activity_a:variant_a() {
	rice::exec true
}

activity_a:variant_b() {
	rice::exec true
}

activity_b() {
	rice::exec true
}

activity_b:variant_a() {
	rice::exec true
}

activity_b:variant_b() {
	rice::exec true
}

activity_c() {
	rice::exec true
}

activity_d() {
	rice::exec true
}

activity_d:variant_a() {
	rice::exec true
}

activity_x() {
	rice::exec true
}

activity_y() {
	rice::exec true
}

rice::add -m meta:system_a
rice::add activity_a
rice::add activity_a:variant_a
rice::add activity_a:variant_b
rice::add activity_b
rice::add activity_b:variant_a
rice::add activity_b:variant_b
rice::add activity_c
rice::add activity_d
rice::add activity_d:variant_a
rice::add -x activity_x
rice::add -x activity_y

