#!/usr/bin/env bash

rice::add -h helper:system_a
helper:system_a() {
	rice::exec true
}

rice::add -x explicit:system_a
explicit:system_a() {
	rice::exec true
}

rice::add implicit:system_a
implicit:system_a() {
	rice::exec true
}

