#!/usr/bin/env bash

meta:system_a() {
	rice::exec true
}

explicit:system_a() {
	rice::exec true
}

implicit:system_a() {
	rice::exec true
}

rice::add -m meta:system_a
rice::add -x explicit:system_a
rice::add implicit:system_a
