#!/usr/bin/env bash

. ricecooker.sh

rice_template_system='mustache'
rice_transaction_audit=true
rice_transaction_lazy=true

meta:freebsd() {
	rice_pkg_install='pkg install'
	rice_pkg_remove='pkg remove'
}

meta:void() {
	rice_pkg_function=rice::pkg_default
	rice_pkg_requires_sudo=true
	rice_pkg_install='xbps-install'
	rice_pkg_install_option_sync='-S'
	rice_pkg_install_option_update='-u'
	rice_pkg_remove='xbps-remove'
	rice_pkg_remove_option_recursive='-R'
	rice_pkg_option_force='-f'
	rice_pkg_option_yes='-y'
	rice_pkg_hold='xbps-pkgdb -m hold'
}

bootstrap:void() {
	rice::pkg -Su
	rice::pkg -i void-repo-nonfree git ruby
	rice::exec sudo gem install mustache
}

bootstrap:void:desktop() {
	rice_template_hash+='.mustache/void_desktop'
	rice::pkg -i nvidia
	rice::info "not installing 'cuda' (/usr/opt)"
}

bootstrap:void:laptop() {
	rice_template_hash+='.mustache/void_laptop'
	sudo vkpurge rm all
	rice::pkg -h linux
	rice::pkg -i linux4.13 linux4.13-headers
	rice::pkg -i xf86-video-intel xf86-video-nouveau
}

system_config:void() {
	# essentials
	rice::pkg neovim ranger git curl tmux fish-shell calcurse calc sc-im 
	# security
	rice::pkg gnupg pass pass-tomb nftables 
	# drives
	rice::pkg udevil bashmount fuse-exfat exfat-utils fuse-sshfs
	# utilities
	rice::pkg htop glances inxi bluez ConsoleKit2 ImageMagick shellcheck \
		exiftool renameutils fdupes unp unrar zip unzip xtools baobab
	# audio
	rice::pkg alsa-utils pulseaudio pamixer pulsemixer pavucontrol apulse mpd mpc ncmpcpp
	# social
	rice::pkg bitlbee bitlbee-facebook
	# X11
	rice::pkg xorg-minimal xf86-input-libinput setxkbmap xrandr xrdb xset xsetroot \
		xbanish numlockx mkfontscale mkfontdir sct
	# desktop environment
	rice::pkg bspwm sxhkd polybar plank xlunch compton dunst alacritty \
		rxvt-unicode urxvt-perls sxiv mpv uzbl uzbl-tabbed
	# document readers
	rice::pkg zathura zathura-djvu zathura-ps zathura-pdf-mupdf mupdf
	# java
	rice::pkg openjdk openjdk-jre
	# big bloated apps
	rice::pkg firefox thunderbird qbittorrent
	# fonts
	rice::pkg font-symbola font-inconsolata-otf font-fira-otf \
		noto-fonts-ttf noto-fonts-emoji ipafont-fonts-otf
	# themes
	rice::pkg xcursor-vanilla-dmz-aa papirus-icon-theme \
		gtk-engine-murrine Adapta

	rice::pkg --commit

	rice::info "not installing 'texlive'"

	rice::bind -tm644 -uroot system/grub /etc/default/grub
	rice::bind -tm644 -uroot system/rc.conf /etc/rc.conf
	rice::bind -tm600 -uroot system/blacklist.conf /etc/modprobe.d/blacklist.conf
	rice::bind -tm640 -uroot system/xorg.conf /etc/X11/xorg.conf
	rice::bind -tm644 -uroot system/sshd_config /etc/ssh/sshd_config
	rice::bind -tm640 -uroot system/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
	rice::bind -tm644 -uroot system/tlp /etc/default/tlp

	rice::info 'managing services'

	rice::exec sudo ln -sf /etc/sv/cgmanager  /var/service/
	rice::exec sudo ln -sf /etc/sv/consolekit /var/service/
	rice::exec sudo ln -sf /etc/sv/dbus       /var/service/
	rice::exec sudo ln -sf /etc/sv/bluetoothd /var/service/
	rice::exec sudo ln -sf /etc/sv/alsa       /var/service/
	rice::exec sudo rm /var/service/agetty-tty{4,5,6}

	rice::info "remember to change your shell (chsh -s /usr/bin/fish)"
}

system_config:void:laptop() {
	return 0
}

system_config:void:desktop() {
	return 0
}

user_keychain() {
	rice::exec mkdir -p ~/.local/etc/certificates

	rice::bind -sm644 keys/adena-ca.pem ~/.local/etc/certificates/adena-ca.pem
	rice::bind -sm644 keys/edu-ca.pem   ~/.local/etc/certificates/edu-ca.pem
	rice::bind -sm600 keys/eduroam.crt  ~/.local/etc/certificates/eduroam.crt
	rice::bind -sm600 keys/eduroam.key  ~/.local/etc/certificates/eduroam.key
	rice::bind -sm644 keys/id_rsa.pub   ~/.ssh/id_rsa.pub
	rice::bind -sm600 keys/id_rsa       ~/.ssh/id_rsa

	rice::exec gpg --import keys/gpg_public.key
	rice::exec gpg --import keys/gpp_secret.key
	rice::exec git clone git@bitbucket.com:maxadamski/password-store ~/.password-store
}

user_config() {
	rice::bind -tm750 X11/xinitrc ~/.xinitrc
	rice::bind -tm750 X11/Xresources ~/.config/X11/Xresources
	rice::bind -tm750 bspwm/bspwmrc ~/.config/bspwm/bspwmrc
	rice::bind -tm750 sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc
	rice::bind -tm640 compton/compton.conf ~/.config/compton.conf
	rice::bind -tm640 gtk/gtkrc-3.0 ~/.config/gtk-3.0/settings.ini
	rice::bind -tm640 gtk/gtkrc-2.0 ~/.gtkrc-2.0
	rice::bind -tm640 polybar/config ~/.config/polybar/config
	rice::bind -tm640 rofi/config ~/.config/rofi/config
	rice::bind -tm640 qutebrowser/config.py ~/.config/qutebrowser/config.py
	rice::bind -tm640 dunst/dunstrc ~/.config/dunst/dunstrc
	rice::bind -tm640 zathura/zathurarc ~/.config/zathura/zathurarc
	rice::bind -tm750 fish/config.fish ~/.config/fish/config.fish
	rice::bind -tm750 shell/inputrc ~/.inputrc
	rice::bind -tm750 shell/bashrc ~/.bashrc
	rice::bind -tm750 git/config ~/.gitconfig
	rice::bind -tm750 git/ignore ~/.gitignore
	rice::bind -tm750 mpd/mpd.conf ~/.config/mpd/mpd.conf
	rice::bind -tm750 mpv/input.conf ~/.config/mpv/input.conf
	rice::bind -tm750 mpv/mpv.conf ~/.config/mpv/mpv.conf
	rice::bind -tm750 ranger/rc.conf ~/.config/ranger/rc.conf
	rice::bind -tm750 ranger/rifle.conf ~/.config/ranger/rifle.conf
	rice::bind -tm750 ranger/scope.sh ~/.config/ranger/scope.sh
	rice::bind -tm750 vim/init.vim ~/.config/nvim/init.vim
	rice::bind -tm750 kitty/kitty.conf ~/.config/kitty/kitty.conf
	rice::bind -dm750 ncmpcpp ~/.config/ncmpcpp
	rice::bind -dm750 fish/functions ~/.config/fish/functions
	rice::bind -dm640 fonts ~/.local/share/fonts
	rice::bind -dm640 walls ~/Pictures/walls
	rice::bind -dm640 bin ~/.local/bin

	rice::info 'creating user directories'

	rice::exec mkdir -p ~/{Desktop,Documents,Downloads,Pictures,Music,Videos}
	rice::exec mkdir -p ~/.local/{bin,etc,opt,share}
	rice::exec mkdir -p ~/.local/share/{themes,icons,fonts}

	rice::info 'symlinking directories'

	rice::exec ln -sf ~/.local/share/themes ~/.themes
	rice::exec ln -sf ~/.local/share/icons ~/.icons
	rice::exec ln -sf ~/.local/share/fonts ~/.fonts

	rice::info 'refreshing font cache'

	rice::exec mkfontscale ~/.local/share/fonts
	rice::exec mkfontdir ~/.local/share/fonts
	rice::exec fc-cache -fv

	rice::info 'installing python user packages'

	rice::exec pip3 install --user pywal pygments neovim

	rice::info "not installing 'anaconda3', 'sbt', 'scala' to '~/.local/opt'"
	rice::info "not setting wallpaper 'wal -i <image>"
}

rice::module -m meta:void meta:freebsd
rice::module -x bootstrap:void
rice::module -x bootstrap:freebsd
rice::module -x bootstrap:void:desktop
rice::module -x bootstrap:void:laptop
rice::module system_config:freebsd:sigma
rice::module system_config:freebsd:zeta
rice::module system_config:void
rice::module system_config:void:desktop
rice::module system_config:void:laptop
rice::module user_packages user_keychain user_config

